import threading
import time
import os
from datetime import datetime
import numpy as np
import cv2

import logging
import config
import ai_features

logger = logging.getLogger(__name__)
import db_handler
import face_recognition as face_rec
from camera.base import CameraBase
from plate_reader import PlateReader


class AIRunner:
    """Background thread that runs AI detection on camera frames and logs events."""

    def __init__(self, cam: CameraBase, mode: str = "yolo", camera_id: str = "CAM_001"):
        self._cam = cam
        self._mode = mode
        self._camera_id = camera_id
        self._running = False
        self._thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self._latest_frame: np.ndarray | None = None
        self._latest_detections: list = []
        self._latest_alerts: list = []
        self._fps: float = 0.0
        # ANPR
        self._anpr_enabled = getattr(config, "ANPR_ENABLED", False)
        self._plate_reader: PlateReader | None = None
        self._anpr_frame_counter = 0
        # Smart logging: track what's currently in frame
        # {detection_key: {"first_seen": time, "last_seen": time, "logged": bool}}
        self._active_detections: dict = {}
        self._stale_timeout = 5.0  # seconds without seeing a detection before it's "gone"

    def start(self) -> None:
        if self._mode in ("facenet", "both"):
            if not face_rec.initialize_system():
                logger.warning("Warning: FaceNet initialization failed. Falling back to YOLO.")
                self._mode = "yolo"

        # Initialize ANPR if enabled
        if self._anpr_enabled:
            self._plate_reader = PlateReader()
            if not self._plate_reader.load():
                logger.warning("ANPR: Tesseract not available. Plate reading disabled.")
                self._anpr_enabled = False

        self._running = True
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()
        logger.info(f"AI Runner started (mode: {self._mode})")

    def stop(self) -> None:
        self._running = False
        if self._thread is not None:
            self._thread.join(timeout=5.0)
            self._thread = None
        logger.info("AI Runner stopped.")

    def get_latest(self) -> tuple[np.ndarray | None, list]:
        with self._lock:
            return self._latest_frame, self._latest_detections.copy()

    def get_pending_alerts(self) -> list:
        """Get and clear any pending alerts generated by smart logging."""
        with self._lock:
            alerts = self._latest_alerts.copy()
            self._latest_alerts.clear()
            return alerts

    @property
    def fps(self) -> float:
        with self._lock:
            return self._fps

    @property
    def anpr_enabled(self) -> bool:
        return self._anpr_enabled

    @anpr_enabled.setter
    def anpr_enabled(self, value: bool) -> None:
        if value and not self._anpr_enabled:
            self._plate_reader = PlateReader()
            if not self._plate_reader.load():
                logger.warning("ANPR: Tesseract not available.")
                return
        self._anpr_enabled = value
        logger.info(f"ANPR {'enabled' if value else 'disabled'}")

    @property
    def mode(self) -> str:
        return self._mode

    @mode.setter
    def mode(self, value: str) -> None:
        if value in ("facenet", "both") and self._mode not in ("facenet", "both"):
            if not face_rec.initialize_system():
                logger.warning("Warning: FaceNet initialization failed.")
                return
        self._mode = value
        logger.info(f"AI Runner mode switched to: {value}")

    def _run_loop(self) -> None:
        frame_count = 0
        fps_start = time.time()
        last_process_time = 0.0
        target_interval = 1.0 / max(getattr(config, "STREAM_TARGET_FPS", 10), 1)

        while self._running:
            frame_bgr = self._cam.get_frame()
            if frame_bgr is None:
                time.sleep(0.01)
                continue

            # Frame skipping: if last frame took longer than target interval,
            # grab the freshest frame and discard stale ones
            if last_process_time > target_interval:
                fresh = self._cam.get_frame()
                if fresh is not None:
                    frame_bgr = fresh

            try:
                process_start = time.time()

                # Keep clean frame for event image saving
                clean_frame = frame_bgr.copy()

                if self._mode == "yolo":
                    annotated, detections = self._run_yolo(frame_bgr)
                elif self._mode == "facenet":
                    annotated, detections = self._run_facenet(frame_bgr)
                elif self._mode == "both":
                    annotated, detections = self._run_both(frame_bgr)
                else:
                    annotated, detections = frame_bgr, []

                last_process_time = time.time() - process_start

                with self._lock:
                    self._latest_frame = annotated
                    self._latest_detections = detections

                # Smart logging: use clean frame for saving (annotated can be corrupted in both mode)
                self._smart_log(clean_frame, annotated, detections)

                frame_count += 1
                elapsed = time.time() - fps_start
                if elapsed >= 1.0:
                    with self._lock:
                        self._fps = frame_count / elapsed
                    frame_count = 0
                    fps_start = time.time()

            except Exception as e:
                logger.error(f"AI Runner error: {e}")
                time.sleep(0.1)

    def _detection_key(self, det: dict) -> str:
        """Generate a unique key for a detection to track it across frames."""
        if det.get("plate_text"):
            return f"plate:{det['plate_text']}"
        elif det.get("name"):
            return f"face:{det['name']}"
        elif det.get("label"):
            return f"obj:{det['label']}"
        return "unknown"

    def _smart_log(self, clean_frame: np.ndarray, annotated_frame: np.ndarray, detections: list) -> None:
        """Log events only when new detections appear, with per-detection cooldown."""
        now = time.time()
        cooldown = getattr(config, "DETECTION_COOLDOWN_SECONDS", 60.0)

        # Build set of current detection keys
        current_keys = set()
        for det in detections:
            key = self._detection_key(det)
            current_keys.add(key)

        # Check for new detections or re-appearances
        new_detections = []
        for det in detections:
            key = self._detection_key(det)

            if key in self._active_detections:
                entry = self._active_detections[key]
                entry["last_seen"] = now

                # Re-log if cooldown has passed since last log
                if entry["logged"] and (now - entry["log_time"] >= cooldown):
                    entry["logged"] = False
            else:
                # Brand new detection — never seen or was gone
                self._active_detections[key] = {
                    "first_seen": now,
                    "last_seen": now,
                    "logged": False,
                    "log_time": 0,
                }

            # Log if not yet logged
            entry = self._active_detections[key]
            if not entry["logged"]:
                new_detections.append(det)
                entry["logged"] = True
                entry["log_time"] = now

        # Log new detections and generate alerts — use annotated frame (with boxes) for saving
        save_frame = annotated_frame if annotated_frame is not None and annotated_frame.mean() >= 1.0 else clean_frame
        if new_detections and save_frame is not None and save_frame.mean() >= 1.0:
            self._log_event(save_frame, new_detections)
            self._generate_alerts(new_detections)

        # Clean up stale detections (not seen for stale_timeout seconds)
        stale_keys = [k for k, v in self._active_detections.items()
                      if now - v["last_seen"] > self._stale_timeout]
        for k in stale_keys:
            del self._active_detections[k]

    def _generate_alerts(self, new_detections: list) -> None:
        """Generate alerts for newly logged detections."""
        if not getattr(config, "ALERT_ENABLED", False):
            return

        alert_events = getattr(config, "ALERT_EVENTS", [])
        alerts = []

        for det in new_detections:
            name = det.get("name", "")
            label = det.get("label", "")

            if "person_detected" in alert_events and label == "person":
                conf = det.get("confidence", 0)
                alerts.append({
                    "type": "person_detected",
                    "title": "Person Detected",
                    "detail": f"person ({conf:.0%} confidence)",
                    "camera": self._camera_id,
                })

            if "unknown_face" in alert_events and name == "Unknown":
                alerts.append({
                    "type": "unknown_face",
                    "title": "Unknown Face",
                    "detail": "Unrecognized face detected",
                    "camera": self._camera_id,
                })

            if "known_face" in alert_events and name and name not in ("Unknown", "No Database", ""):
                alerts.append({
                    "type": "known_face",
                    "title": f"{name} Detected",
                    "detail": f"Known person: {name}",
                    "camera": self._camera_id,
                })

            # Watchlist plate
            plate_text = det.get("plate_text", "")
            if "watchlist_plate" in alert_events and plate_text and det.get("is_watchlist"):
                alerts.append({
                    "type": "watchlist_plate",
                    "title": f"Watchlist Plate: {plate_text}",
                    "detail": det.get("watchlist_label", plate_text),
                    "camera": self._camera_id,
                })

        if alerts:
            with self._lock:
                self._latest_alerts.extend(alerts)

    def _run_yolo(self, frame_bgr: np.ndarray) -> tuple[np.ndarray, list]:
        # Auto-include vehicle classes when ANPR is enabled
        classes = list(config.DETECTION_CLASSES)
        if self._anpr_enabled:
            vehicle_classes = getattr(config, "ANPR_VEHICLE_CLASSES", ["car", "truck", "bus", "motorcycle"])
            for vc in vehicle_classes:
                if vc not in classes:
                    classes.append(vc)

        analyzed_frame, detected_data = ai_features.run_yolov8_detection(
            frame_bgr, self._cam.frame_size,
            roi=None, classes_filter=classes
        )
        detections = []
        for item in detected_data:
            if isinstance(item, tuple) and len(item) >= 2:
                det = {"label": item[0], "confidence": round(item[1], 3)}
                if len(item) >= 3:
                    det["bbox"] = item[2]
                detections.append(det)

        # ANPR: read plates from vehicle detections
        if self._anpr_enabled and self._plate_reader and self._plate_reader.is_loaded:
            self._anpr_frame_counter += 1
            interval = getattr(config, "ANPR_FRAME_INTERVAL", 5)
            if self._anpr_frame_counter % interval == 0:
                vehicle_classes = getattr(config, "ANPR_VEHICLE_CLASSES", ["car", "truck", "bus", "motorcycle"])
                min_width = getattr(config, "ANPR_MIN_VEHICLE_WIDTH", 100)
                h_frame, w_frame = frame_bgr.shape[:2]
                scale = max(w_frame / 640, 0.5)
                font_scale = 0.4 * scale
                thickness = max(1, int(1 * scale))

                for det in detections:
                    if det.get("label") not in vehicle_classes:
                        continue
                    bbox = det.get("bbox")
                    if not bbox:
                        continue
                    x1, y1, x2, y2 = bbox
                    if (x2 - x1) < min_width:
                        continue

                    # Crop vehicle and read plate
                    vehicle_crop = frame_bgr[y1:y2, x1:x2]
                    result = self._plate_reader.read_plate(vehicle_crop)
                    if result:
                        plate_det = {
                            "type": "plate",
                            "plate_text": result["text"],
                            "confidence": result["confidence"],
                            "vehicle_label": det["label"],
                        }
                        # Check watchlist
                        wl = db_handler.check_plate_watchlist(result["text"])
                        if wl:
                            plate_det["is_watchlist"] = True
                            plate_det["watchlist_label"] = wl.get("label", "")

                        detections.append(plate_det)

                        # Draw plate text on frame
                        cv2.putText(analyzed_frame, result["text"], (x1, y2 + int(20 * scale)),
                                    cv2.FONT_HERSHEY_SIMPLEX, font_scale, (0, 255, 255), thickness)

        return analyzed_frame, detections

    def _run_facenet(self, frame_bgr: np.ndarray) -> tuple[np.ndarray, list]:
        if frame_bgr.dtype != np.uint8:
            frame_bgr = frame_bgr.astype(np.uint8)

        analyzed_frame, detected_data = face_rec.run_facenet_recognition(
            frame_bgr, self._cam.frame_size
        )
        # Don't call process_deferred_logs() — smart logging handles event saving

        # detected_data is list of (display_name, 1.0 - distance) tuples
        detections = []
        for item in detected_data:
            if isinstance(item, dict):
                detections.append(item)
            elif isinstance(item, tuple) and len(item) >= 2:
                name = item[0]
                confidence = round(item[1], 3)  # 1.0 - distance (higher = better match)
                detections.append({"name": name, "confidence": confidence})
        return analyzed_frame, detections

    def _run_both(self, frame_bgr: np.ndarray) -> tuple[np.ndarray, list]:
        """Run YOLO and FaceNet on the same frame, merge results."""
        if frame_bgr.dtype != np.uint8:
            frame_bgr = frame_bgr.astype(np.uint8)

        # YOLO on clean frame — returns annotated frame with object boxes
        yolo_frame, yolo_dets = ai_features.run_yolov8_detection(
            frame_bgr.copy(), self._cam.frame_size,
            roi=None, classes_filter=config.DETECTION_CLASSES
        )

        # FaceNet on clean frame — returns annotated frame with face boxes
        face_frame, face_data = face_rec.run_facenet_recognition(
            frame_bgr.copy(), self._cam.frame_size
        )
        # Don't call process_deferred_logs() — smart logging handles event saving

        # Simple merge: draw face_frame on top of yolo_frame using addWeighted
        # This preserves both sets of annotations clearly
        combined = cv2.addWeighted(yolo_frame, 0.5, face_frame, 0.5, 0)
        # Re-overlay annotations by keeping the brighter pixels from either frame
        # (annotations are drawn in bright colors on dark background)
        combined = np.maximum(yolo_frame, face_frame)

        # Merge detections
        detections = []
        for item in yolo_dets:
            if isinstance(item, tuple) and len(item) >= 2:
                det = {"type": "yolo", "label": item[0], "confidence": round(item[1], 3)}
                if len(item) >= 3:
                    det["bbox"] = item[2]
                detections.append(det)

        for item in face_data:
            if isinstance(item, dict):
                item["type"] = "face"
                detections.append(item)
            elif isinstance(item, tuple) and len(item) >= 2:
                detections.append({"type": "face", "name": item[0], "confidence": round(item[1], 3)})

        return combined, detections

    def _log_event(self, frame: np.ndarray, detections: list) -> None:
        """Save an event image and log to database."""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

            # Skip black/empty frames
            if frame is None or frame.mean() < 1.0:
                return

            # Skip if low disk space
            from web.utils import has_disk_space
            if not has_disk_space():
                logger.warning("Low disk space — skipping event image save")
                return

            # Separate detections by type
            yolo_dets = [d for d in detections if d.get("label") and not d.get("name") and not d.get("plate_text")]
            face_dets = [d for d in detections if d.get("name")]
            plate_dets = [d for d in detections if d.get("plate_text")]

            # Save and log YOLO detections
            if yolo_dets:
                img_dir = config.ROI_OUTPUT_DIR
                os.makedirs(img_dir, exist_ok=True)
                image_filename = f"det_{timestamp}.jpg"
                cv2.imwrite(os.path.join(img_dir, image_filename), frame)

                for det in yolo_dets:
                    db_handler.log_detection(
                        detection_data=[{"class": det.get("label", "unknown"), "confidence": det.get("confidence", 0)}],
                        roi_area=None,
                        image_filename=image_filename,
                        camera_id=self._camera_id,
                    )

            # Save and log face detections (to event_images/)
            if face_dets:
                img_dir = config.EVENT_IMAGE_DIR
                os.makedirs(img_dir, exist_ok=True)
                image_filename = f"face_{timestamp}.jpg"
                cv2.imwrite(os.path.join(img_dir, image_filename), frame)

                for det in face_dets:
                    name = det.get("name", "Unknown")
                    confidence = det.get("confidence", 0)
                    distance = 1.0 - confidence
                    is_known = name != "Unknown" and distance < config.RECOGNITION_THRESHOLD
                    db_handler.log_face_detection_event(
                        name=name,
                        distance=distance,
                        image_filename=image_filename,
                        camera_id=self._camera_id,
                        is_known=is_known
                    )

            # Save and log plate detections
            if plate_dets:
                img_dir = getattr(config, "PLATE_IMAGE_DIR", "plate_images")
                os.makedirs(img_dir, exist_ok=True)
                image_filename = f"plate_{timestamp}.jpg"
                cv2.imwrite(os.path.join(img_dir, image_filename), frame)

                for det in plate_dets:
                    wl = db_handler.check_plate_watchlist(det["plate_text"])
                    db_handler.log_plate_event(
                        plate_text=det["plate_text"],
                        vehicle_type=det.get("vehicle_label", "vehicle"),
                        confidence=det.get("confidence", 0),
                        image_filename=image_filename,
                        is_watchlist=bool(wl),
                        watchlist_id=wl["id"] if wl else None,
                        camera_id=self._camera_id,
                    )

        except Exception as e:
            logger.error(f"AI Runner logging error: {e}")
