import threading
import time
import os
from datetime import datetime
import numpy as np
import cv2

import config
import ai_features
import db_handler
import face_recognition as face_rec
from camera.base import CameraBase


class AIRunner:
    """Background thread that runs AI detection on camera frames and logs events."""

    def __init__(self, cam: CameraBase, mode: str = "yolo", camera_id: str = "CAM_001"):
        self._cam = cam
        self._mode = mode
        self._camera_id = camera_id
        self._running = False
        self._thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self._latest_frame: np.ndarray | None = None
        self._latest_detections: list = []
        self._latest_alerts: list = []
        self._fps: float = 0.0
        # Smart logging: track what's currently in frame
        # {detection_key: {"first_seen": time, "last_seen": time, "logged": bool}}
        self._active_detections: dict = {}
        self._stale_timeout = 5.0  # seconds without seeing a detection before it's "gone"

    def start(self) -> None:
        if self._mode == "facenet":
            if not face_rec.initialize_system():
                print("Warning: FaceNet initialization failed. Falling back to YOLO.")
                self._mode = "yolo"

        self._running = True
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()
        print(f"AI Runner started (mode: {self._mode})")

    def stop(self) -> None:
        self._running = False
        if self._thread is not None:
            self._thread.join(timeout=5.0)
            self._thread = None
        print("AI Runner stopped.")

    def get_latest(self) -> tuple[np.ndarray | None, list]:
        with self._lock:
            return self._latest_frame, self._latest_detections.copy()

    def get_pending_alerts(self) -> list:
        """Get and clear any pending alerts generated by smart logging."""
        with self._lock:
            alerts = self._latest_alerts.copy()
            self._latest_alerts.clear()
            return alerts

    @property
    def fps(self) -> float:
        with self._lock:
            return self._fps

    @property
    def mode(self) -> str:
        return self._mode

    @mode.setter
    def mode(self, value: str) -> None:
        if value in ("facenet", "both") and self._mode not in ("facenet", "both"):
            if not face_rec.initialize_system():
                print("Warning: FaceNet initialization failed.")
                return
        self._mode = value
        print(f"AI Runner mode switched to: {value}")

    def _run_loop(self) -> None:
        frame_count = 0
        fps_start = time.time()

        while self._running:
            frame_bgr = self._cam.get_frame()
            if frame_bgr is None:
                time.sleep(0.01)
                continue

            try:
                # Keep clean frame for event image saving
                clean_frame = frame_bgr.copy()

                if self._mode == "yolo":
                    annotated, detections = self._run_yolo(frame_bgr)
                elif self._mode == "facenet":
                    annotated, detections = self._run_facenet(frame_bgr)
                elif self._mode == "both":
                    annotated, detections = self._run_both(frame_bgr)
                else:
                    annotated, detections = frame_bgr, []

                with self._lock:
                    self._latest_frame = annotated
                    self._latest_detections = detections

                # Smart logging: use clean frame for saving (annotated can be corrupted in both mode)
                self._smart_log(clean_frame, annotated, detections)

                frame_count += 1
                elapsed = time.time() - fps_start
                if elapsed >= 1.0:
                    with self._lock:
                        self._fps = frame_count / elapsed
                    frame_count = 0
                    fps_start = time.time()

            except Exception as e:
                print(f"AI Runner error: {e}")
                time.sleep(0.1)

    def _detection_key(self, det: dict) -> str:
        """Generate a unique key for a detection to track it across frames."""
        if det.get("name"):
            # Face detection: key by person name
            return f"face:{det['name']}"
        elif det.get("label"):
            # YOLO detection: key by object class
            return f"obj:{det['label']}"
        return "unknown"

    def _smart_log(self, clean_frame: np.ndarray, annotated_frame: np.ndarray, detections: list) -> None:
        """Log events only when new detections appear, with per-detection cooldown."""
        now = time.time()
        cooldown = getattr(config, "DETECTION_COOLDOWN_SECONDS", 60.0)

        # Build set of current detection keys
        current_keys = set()
        for det in detections:
            key = self._detection_key(det)
            current_keys.add(key)

        # Check for new detections or re-appearances
        new_detections = []
        for det in detections:
            key = self._detection_key(det)

            if key in self._active_detections:
                entry = self._active_detections[key]
                entry["last_seen"] = now

                # Re-log if cooldown has passed since last log
                if entry["logged"] and (now - entry["log_time"] >= cooldown):
                    entry["logged"] = False
            else:
                # Brand new detection — never seen or was gone
                self._active_detections[key] = {
                    "first_seen": now,
                    "last_seen": now,
                    "logged": False,
                    "log_time": 0,
                }

            # Log if not yet logged
            entry = self._active_detections[key]
            if not entry["logged"]:
                new_detections.append(det)
                entry["logged"] = True
                entry["log_time"] = now

        # Log new detections and generate alerts — use clean frame for saving
        save_frame = clean_frame if clean_frame is not None and clean_frame.mean() >= 1.0 else annotated_frame
        if new_detections and save_frame is not None and save_frame.mean() >= 1.0:
            self._log_event(save_frame, new_detections)
            self._generate_alerts(new_detections)

        # Clean up stale detections (not seen for stale_timeout seconds)
        stale_keys = [k for k, v in self._active_detections.items()
                      if now - v["last_seen"] > self._stale_timeout]
        for k in stale_keys:
            del self._active_detections[k]

    def _generate_alerts(self, new_detections: list) -> None:
        """Generate alerts for newly logged detections."""
        if not getattr(config, "ALERT_ENABLED", False):
            return

        alert_events = getattr(config, "ALERT_EVENTS", [])
        alerts = []

        for det in new_detections:
            name = det.get("name", "")
            label = det.get("label", "")

            if "person_detected" in alert_events and label == "person":
                conf = det.get("confidence", 0)
                alerts.append({
                    "type": "person_detected",
                    "title": "Person Detected",
                    "detail": f"person ({conf:.0%} confidence)",
                    "camera": self._camera_id,
                })

            if "unknown_face" in alert_events and name == "Unknown":
                alerts.append({
                    "type": "unknown_face",
                    "title": "Unknown Face",
                    "detail": "Unrecognized face detected",
                    "camera": self._camera_id,
                })

            if "known_face" in alert_events and name and name not in ("Unknown", "No Database", ""):
                alerts.append({
                    "type": "known_face",
                    "title": f"{name} Detected",
                    "detail": f"Known person: {name}",
                    "camera": self._camera_id,
                })

        if alerts:
            with self._lock:
                self._latest_alerts.extend(alerts)

    def _run_yolo(self, frame_bgr: np.ndarray) -> tuple[np.ndarray, list]:
        analyzed_frame, detected_data = ai_features.run_yolov8_detection(
            frame_bgr, self._cam.frame_size,
            roi=None, classes_filter=config.DETECTION_CLASSES
        )
        detections = []
        for item in detected_data:
            if isinstance(item, tuple) and len(item) == 2:
                detections.append({"label": item[0], "confidence": round(item[1], 3)})
        return analyzed_frame, detections

    def _run_facenet(self, frame_bgr: np.ndarray) -> tuple[np.ndarray, list]:
        if frame_bgr.dtype != np.uint8:
            frame_bgr = frame_bgr.astype(np.uint8)

        analyzed_frame, detected_data = face_rec.run_facenet_recognition(
            frame_bgr, self._cam.frame_size
        )
        # Don't call process_deferred_logs() — smart logging handles event saving

        # detected_data is list of (display_name, 1.0 - distance) tuples
        detections = []
        for item in detected_data:
            if isinstance(item, dict):
                detections.append(item)
            elif isinstance(item, tuple) and len(item) >= 2:
                name = item[0]
                confidence = round(item[1], 3)  # 1.0 - distance (higher = better match)
                detections.append({"name": name, "confidence": confidence})
        return analyzed_frame, detections

    def _run_both(self, frame_bgr: np.ndarray) -> tuple[np.ndarray, list]:
        """Run YOLO and FaceNet on the same frame, merge results."""
        if frame_bgr.dtype != np.uint8:
            frame_bgr = frame_bgr.astype(np.uint8)

        # YOLO on clean frame — returns annotated frame with object boxes
        yolo_frame, yolo_dets = ai_features.run_yolov8_detection(
            frame_bgr.copy(), self._cam.frame_size,
            roi=None, classes_filter=config.DETECTION_CLASSES
        )

        # FaceNet on clean frame — returns annotated frame with face boxes
        face_frame, face_data = face_rec.run_facenet_recognition(
            frame_bgr.copy(), self._cam.frame_size
        )
        # Don't call process_deferred_logs() — smart logging handles event saving

        # Simple merge: draw face_frame on top of yolo_frame using addWeighted
        # This preserves both sets of annotations clearly
        combined = cv2.addWeighted(yolo_frame, 0.5, face_frame, 0.5, 0)
        # Re-overlay annotations by keeping the brighter pixels from either frame
        # (annotations are drawn in bright colors on dark background)
        combined = np.maximum(yolo_frame, face_frame)

        # Merge detections
        detections = []
        for item in yolo_dets:
            if isinstance(item, tuple) and len(item) == 2:
                detections.append({"type": "yolo", "label": item[0], "confidence": round(item[1], 3)})

        for item in face_data:
            if isinstance(item, dict):
                item["type"] = "face"
                detections.append(item)
            elif isinstance(item, tuple) and len(item) >= 2:
                detections.append({"type": "face", "name": item[0], "confidence": round(item[1], 3)})

        return combined, detections

    def _log_event(self, frame: np.ndarray, detections: list) -> None:
        """Save an event image and log to database."""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

            # Skip black/empty frames
            if frame is None or frame.mean() < 1.0:
                return

            # Separate detections by type
            yolo_dets = [d for d in detections if d.get("label") and not d.get("name")]
            face_dets = [d for d in detections if d.get("name")]

            # Save and log YOLO detections
            if yolo_dets:
                img_dir = config.ROI_OUTPUT_DIR
                os.makedirs(img_dir, exist_ok=True)
                image_filename = f"det_{timestamp}.jpg"
                cv2.imwrite(os.path.join(img_dir, image_filename), frame)

                for det in yolo_dets:
                    db_handler.log_detection(
                        detection_data=[{"class": det.get("label", "unknown"), "confidence": det.get("confidence", 0)}],
                        roi_area=None,
                        image_filename=image_filename,
                        camera_id=self._camera_id,
                    )

            # Save and log face detections (to event_images/)
            if face_dets:
                img_dir = config.EVENT_IMAGE_DIR
                os.makedirs(img_dir, exist_ok=True)
                image_filename = f"face_{timestamp}.jpg"
                cv2.imwrite(os.path.join(img_dir, image_filename), frame)

                for det in face_dets:
                    name = det.get("name", "Unknown")
                    confidence = det.get("confidence", 0)
                    distance = 1.0 - confidence
                    is_known = name != "Unknown" and distance < config.RECOGNITION_THRESHOLD
                    db_handler.log_face_detection_event(
                        name=name,
                        distance=distance,
                        image_filename=image_filename,
                        camera_id=self._camera_id,
                        is_known=is_known
                    )

        except Exception as e:
            print(f"AI Runner logging error: {e}")
